const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');

// Load .env.local manually
const envPath = path.resolve(process.cwd(), '.env.local');
const envContent = fs.readFileSync(envPath, 'utf8');

const envConfig = {};
envContent.split('\n').forEach(line => {
    const [key, ...value] = line.split('=');
    if (key && value) {
        envConfig[key.trim()] = value.join('=').trim();
    }
});

const supabaseUrl = envConfig.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = envConfig.NEXT_PUBLIC_SUPABASE_ANON_KEY;

const supabase = createClient(supabaseUrl, supabaseKey);

// Runner prompt içeriği
const runnerPrompt = `Which image do you think was generated by the Nano Banana Pro?

{
  "subject": {
    "description": "A side-profile shot of an athletic Black male runner mid-stride, captured in a high-energy sports editorial poster style. The image features mixed media elements with neon lime green scribbles outlining his body.",
    "mirror_rules": "not_applicable",
    "age": "20-30 years old",
    "expression": {
      "eyes": {
        "look": "focused forward",
        "energy": "determined",
        "direction": "right"
      },
      "mouth": {
        "position": "slightly open breathing",
        "energy": "intense"
      },
      "overall": "in the zone, meditative flow state"
    }
  },
  "photography": {
    "camera_style": "sports editorial mixed with graphic design poster",
    "angle": "eye-level tracking shot, side profile",
    "shot_type": "full body, wide shot",
    "aspect_ratio": "3:4 vertical poster"
  },
  "the_vibe": {
    "energy": "kinetic and rhythmic",
    "mood": "disciplined, motivating, healing",
    "aesthetic": "modern sports zine, street style graphic design"
  }
}`;

async function fixPrompts() {
    console.log("=== Prompt Düzeltme ===\n");

    try {
        // 1. UUID prompt'tan tam bilgiyi al
        console.log("1. UUID prompt kontrol ediliyor...");

        const { data: uuidPrompt, error: uuidError } = await supabase
            .from('banana_prompts')
            .select('*')
            .eq('id', '01db68cd-9ff1-487e-8885-2eaa49ff03e3')
            .single();

        if (uuidError) {
            console.log("  UUID prompt bulunamadı:", uuidError.message);
        } else {
            console.log("  UUID prompt bulundu:");
            console.log("    Title:", uuidPrompt.title);
            console.log("    Images:", JSON.stringify(uuidPrompt.images));
        }

        // 2. #02953'ü doğru içerikle güncelle
        console.log("\n2. #02953 güncelleniyor...");

        const updateData = {
            title: "Athletic Runner - Sports Editorial Poster",
            prompt: runnerPrompt,
            summary: "Athletic Black male runner in dynamic mid-stride pose with neon green graphic overlays",
            author: "@BotFusionsS",
            images: [
                "https://pbs.twimg.com/media/G853Mz4bEAANDNB?format=jpg&name=small",
                "https://pbs.twimg.com/media/G853MzvagAECxtt?format=jpg&name=small"
            ],
            categories: ["photography", "portrait", "creative", "sports"],
            source: "BotsNANO"
        };

        const { error: updateError } = await supabase
            .from('banana_prompts')
            .update(updateData)
            .eq('id', '02953');

        if (updateError) {
            console.log("  Güncelleme başarısız (RLS?):", updateError.message);
            console.log("  Manuel SQL gerekebilir.");
        } else {
            console.log("  ✓ Güncelleme komutu gönderildi");
        }

        // 3. Doğrula
        console.log("\n3. Doğrulama...");

        const { data: verify, error: verifyError } = await supabase
            .from('banana_prompts')
            .select('id, title, prompt, images')
            .eq('id', '02953')
            .single();

        if (verify) {
            console.log("  #02953 durumu:");
            console.log("    Title:", verify.title);
            console.log("    Prompt length:", verify.prompt?.length || 0);
            console.log("    Images:", verify.images?.length || 0, "adet");
        }

        // UUID prompt'u silme bilgisi
        console.log("\n\n=== MANUEL İŞLEM GEREKLİ ===");
        console.log("Supabase Dashboard'da şu SQL'i çalıştırın:\n");
        console.log(`-- #02953'ü güncelle
UPDATE banana_prompts 
SET 
  title = 'Athletic Runner - Sports Editorial Poster',
  prompt = 'Which image do you think was generated by the Nano Banana Pro? A side-profile shot of an athletic Black male runner mid-stride, captured in a high-energy sports editorial poster style with neon lime green scribbles outlining his body.',
  summary = 'Athletic Black male runner in dynamic mid-stride pose with neon green graphic overlays',
  author = '@BotFusionsS',
  images = ARRAY['https://pbs.twimg.com/media/G853Mz4bEAANDNB?format=jpg&name=small', 'https://pbs.twimg.com/media/G853MzvagAECxtt?format=jpg&name=small'],
  source = 'BotsNANO'
WHERE id = '02953';

-- Yinelenen UUID prompt'u sil
DELETE FROM banana_prompts WHERE id = '01db68cd-9ff1-487e-8885-2eaa49ff03e3';
`);

    } catch (err) {
        console.error("Script hatası:", err);
    }
}

fixPrompts();
